export enum ReconocimientoTipo {
  GENERAL = 'GENERAL',
  TALLERISTA = 'TALLERISTA',
  CONFERENCISTA = 'CONFERENCISTA',
  HACKATON_EVALUADOR = 'HACKATON_EVALUADOR',
  HACKATON_PREMIACION = 'HACKATON_PREMIACION',
}
